### PR TITLE
Adding some of DDAmico's files for LASSO, UFS MRW, and SCM comparisons

### PR DESCRIPTION
**Pull request by ddamicoWX10**
Only a selection of files used for post-processing. More can be added if needed. These files mainly deal with LASSO SID8 on 20190714, but they are adaptable.

### CODE REVIEW

**Comment by bluefinweiwei** [comment]
Thanks Dan. Would you mind also pushing the scripts about Wangara case? Ideally, also push the code for batching SCM and LASSO cases (multiseasonal analysis)? If DTC use these code/scripts in any future activities, we will give you credit for sure (I can try to add a tag/notice for these code). Thanks!

**Comment by ddamicoWX10** [comment]
I forgot to make new branches for all of these new commits, so they are all under master right now. We can close this pull request and I can contribute the individual branches and run new pull requests, or they can be merged as is into NCAR:master.

**Comment by bluefinweiwei** [comment]
Creating an individual branch sounds more reasonable, since SCM analysis is very different from for the ones for global forecasts. Yes, please go ahead and close this PR and resubmit another one. Thanks!

**Comment by ligiabernardet** [comment]
How about putting the SCM diagnostics under their own directory (called
something like SCM) on the master?

**Comment by ddamicoWX10** [comment]
Closed pull request and going to reorganize and open new pull requests with different branches.

**Pull request closed without merging**
